version: '3.8'

services:
  db:
    image: postgres:17.1
    container_name: go-fullstack-db
    environment:
      POSTGRES_DB: go-fullstack
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: